name: FloodgateSkinDisabler
version: '1.0.0'
main: com.github.cedricrev.floodgateskindisabler.FloodgateSkinDisabler
api-version: '1.21'
authors: [ CedricRev ]
description: Disables skins
website: https://github.com/CedricRev
depend: ["floodgate"]